### ISSUE TITLE
`Process finished with exit code -1073741819 (0xC0000005)` when running vpselector in a for loop

### ISSUE THREAD

**Issue by saiyalamarty** [manumerous/visual_dataframe_selector#23]
Challenge: The dataset I have is too large to feed to vpselector in one go. Nothing wrong with vpselector, but I feel it will be better to pass smaller data chunks so that I don't have to zoom in to see the granularity in the data before i make the selection.

I am trying to call `vpselector.data_selection.select_visual_data(sub_df, plot_config_dict)` inside a for loop, but after I make the selections in the second data chunk, my code exits. No error, but I get `Process finished with exit code -1073741819 (0xC0000005)`. Google says this exit code is somehow related to memory corruption or overflows.

Upon debugging, I see that the second selection works, and code reaches https://github.com/manumerous/vpselector/blob/master/src/vpselector/data_selection.py#L18. But after this, it is unable to assign the selected df to my variable.

Here is my test code, I can reproduce this by running on the test.csv
To enable the chunk loop, decrease the chunk size from 4000 to 2000. The test.csv has ~3000 rows.

```python
# Based on https://github.com/manumerous/vpselector/blob/master/vpselector_example.py

import warnings
from pathlib import Path

import pandas as pd
import vpselector


warnings.filterwarnings("ignore")


def test_vpselector():
    test_file_path = Path() / "test.csv"
    print(test_file_path)
    plot_config_dict = {
        "x_axis_col": "timestamp",
        "sub_plt1_data": ["q0", "q1", "q2", "q3"],
        "sub_plt2_data": ["u0", "u1", "u2", "u3", "u4", "u5", "u6", "u7"],
    }
    data_df = pd.read_csv(test_file_path, index_col=0)
    data_df["label"] = 0

    print(data_df["label"].value_counts())

    chunk_size = 4000
    for i in range(0, len(data_df), chunk_size):
        sub_df = data_df.iloc[i: i + chunk_size]

        selected_df = vpselector.data_selection.select_visual_data(sub_df, plot_config_dict)

        if selected_df.empty:
            continue

        data_df.loc[selected_df["old_index"], "label"] = 1

    print(data_df["label"].value_counts())

    return


if __name__ == "__main__":
    test_vpselector()
```

**Comment by saiyalamarty** [comment]
okay, my ignorance. You already have a method to use if we have a PyQt5 app. That seems to work for my use case.

I created an empty PyQt5 app instance and then passed that instance like `vpselector.data_selection.select_visual_data_in_pyqt_app(sub_df, plot_config_dict, app)` instead of using `vpselector.data_selection.select_visual_data` and that seemed to work.

**Comment by manumerous** [comment]
Thanks for reporting this. I think this could be related to the problem of running multiple pyqt apps at the same time when running multiple successive calls of the vpselector. There might be a more proper way to fix this by calling the Qapplications `app.quit()` to properly de-allocate all memory related to the app before creating a new one. 

The workaround with passing in the same Qapplication is a great idea for now. I plan to eventually look into this issue a bit deeper now that I am aware of it thanks to your issue. But suggestions to fix it are also welcome. :)
