### ISSUE TITLE
Jupyter Notebook (Google Colab)

### ISSUE THREAD

**Issue by firmai** [manumerous/visual_dataframe_selector#24]
This could take-off if you create it for JN.

**Comment by manumerous** [comment]
Thanks for the great suggestion Derek! I totally agree. I will attempt that once i find time for this project again. Any help is welcome if you have experience with UI applications in Jupiter Notebooks :)

**Comment by pranavchougule03** [comment]
I want to contribute to the project I saw your ad on upwork. May I give a try?

**Comment by manumerous** [comment]
Of course you are very welcome to do so @pranavchougule03 !

I know somebody is already working on the Jupyter notebook implementation. Would you maybe be interested in working on #13 ? But I am also very open to other suggestions :)

**Comment by manumerous** [comment]
Feel free to open issues and PRs. I am happy to help and discuss. :)
